#!/usr/bin/env bash

# Save the arguments to environment variable
export STELLAR_ARGS="$@"

set -e

REFLECTOR_MOUNT_DIR="/reflector-node/app/home"

# Check if the REFLECTOR_MOUNT_DIR directory is a mount point
if ! mountpoint -q "$REFLECTOR_MOUNT_DIR"; then
    echo "ERROR: $REFLECTOR_MOUNT_DIR is not mounted!"
    exit 1
fi

STELLAR_MOUNT_DIR="/opt/stellar"

# Check if the STELLAR_MOUNT_DIR directory is a mount point
if ! mountpoint -q "$STELLAR_MOUNT_DIR"; then
    echo "ERROR: $STELLAR_MOUNT_DIR is not mounted!"
    exit 1
fi

PASSWORD_FILE="$REFLECTOR_MOUNT_DIR/.dockerDbPassword"

# Check if the .dockerDbPassword file exists
if [ ! -f "$PASSWORD_FILE" ]; then
    echo ".dockerDbPassword file not found! Generating a new password..."
    # Generate a random password for the database
    DOCKER_DB_PASSWORD=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' |  head -c 16)
    
    # Save the password to the .dockerDbPassword file
    echo $DOCKER_DB_PASSWORD > "$PASSWORD_FILE"
else
    DOCKER_DB_PASSWORD=$(cat "$PASSWORD_FILE")
fi

# Set the password as the POSTGRES_PASSWORD environment variable
export POSTGRES_PASSWORD=$DOCKER_DB_PASSWORD
SUPERVISORD_CONFIG="/etc/supervisor/conf.d/supervisord.conf"

# Ensure /reflector-node/app/home/docker/logs/ and /opt/stellar/logs/ exists
mkdir -p /reflector-node/app/home/docker/logs/
mkdir -p /opt/stellar/logs/

# Start the services using the supervisord configuration
exec /usr/bin/supervisord -c $SUPERVISORD_CONFIG